module.exports = [
    {
        captainName: "Picard",
        title: "Courage",
        post: "Courage can be an emotion too.",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 100,
    },
    {
        captainName: "Ahab",
        title: "Whale",
        post: "By heavens man, we are turned round and round in this world, like yonder windlass, and fate is the handspike.",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 20,
    },
    {
        captainName: "Sarah Lance",
        title: "Vandal Savage",
        post: "I’d tell you to go to hell, but you’d probably just feel at home there.",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 0,
    },
    {
        captainName: "Ahab",
        title: "Insolence",
        post: "I don't give reasons. I give orders!",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 100,
    },
    {
        captainName: "Sarah Lance",
        title: "Ava",
        post: "Ava's the kind of girl that you take home to your parents, and I am the kind you take to an exorcism",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 0,
    },
    {
        captainName: "Ahab",
        title: "What is sleep?",
        post: "Sleep? That bed is a coffin, and those are winding sheets. I do not sleep, I die.",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 5,
    },
    {
        captainName: "Sarah Lance",
        title: "Jonah Hex",
        post: "I know you don’t like taking orders from a woman, but you’re gonna like getting your ass kicked by one even less.",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 0,
    },
    {
        captainName: "Han Solo",
        title: "Star Wars",
        post: "Laugh it up, Fuzzball",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 6,
    },
    {
        captainName: "Captain Jack Sparrow",
        title: "Pirates of the Carribean",
        post: "Why is the Rum gone?",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 40,
    },
    {
        captainName: "Captain Babossa",
        title: "Pirates of the Carribean",
        post: "We named the Monkey Jack",
        mistakesWereMadeToday: true,
        daysSinceLastCrisis: 7,
    },
];